# Generated by Django 4.2.2 on 2023-07-12 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_mentee_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='experise',
            new_name='expertise',
        ),
    ]
