# Generated by Django 4.2.2 on 2023-07-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_experise_mentor_expertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='experience',
            field=models.IntegerField(null=True),
        ),
    ]
