# Generated by Django 4.2.2 on 2023-07-12 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_mentor_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='favorites',
            field=models.ManyToManyField(null=True, related_name='favorites', to='users.mentor'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='expertise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.expertise'),
        ),
    ]
