# Generated by Django 4.2.2 on 2023-07-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_mentee_favorites_alter_mentor_expertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to='users.mentor'),
        ),
    ]
