# Generated by Django 4.2.2 on 2023-07-13 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_mentee_favorites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentor",
            name="expertise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.expertise",
            ),
        ),
    ]
