# Generated by Django 4.2.2 on 2023-07-13 14:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_mentor_expertise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentor",
            name="experience",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "rating",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "mentee_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.mentee"
                    ),
                ),
                (
                    "mentor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.mentor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mentee_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.mentee"
                    ),
                ),
                (
                    "mentor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.mentor"
                    ),
                ),
            ],
        ),
    ]
