# Generated by Django 4.2.2 on 2023-07-17 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_rename_mentee_id_review_mentee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentor",
            name="expertise",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.expertise",
            ),
        ),
    ]
