# Generated by Django 4.2.2 on 2023-07-31 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_rename_session_bookedsession_mentorsession_and_more'),
        ('users', '0012_mentorsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MentorSession',
        ),
    ]
