steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  script: |
    #!/usr/bin/env bash
    echo $GCP_CRED > cred_file
    gcloud auth login --cred-file=cred_file
    gsutil cp gs://secret_id_rsa/id_rsa .
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ecomercebackend-393408/cs428-backend:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ecomercebackend-393408/cs428-backend:latest']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'scp', '--zone', 'asia-southeast1-b', 'remote_startup.sh',  'ecom-1:/home/quocthogminhqtm/']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', 'ecom-1', '--zone', 'asia-southeast1-b', '--command', 'bash /home/quocthogminhqtm/remote_startup.sh']
options:
  logging: GCS_ONLY
  env: 
  - 'GCP_PROJECT=$PROJECT_ID'
  - 'CLOUDSDK_CORE_PROJECT=$PROJECT_ID'
  - 'GCP_CRED=$_SECRET_GCP_CREDENTIAL'
    
    

