steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  env: 
    - 'GCP_PROJECT=$PROJECT_ID'
    - 'CLOUDSDK_CORE_PROJECT=$PROJECT_ID'
    - 'GCP_INSTANCE=instance-1'
    - 'GIT_FOLDER=cs428-backend'
    - 'GCP_CE_ZONE=us-central1-a'
    - 'GCP_CRED=$_SECRET_GCP_CREDENTIAL'
  script: |
    #!/usr/bin/env bash
    echo $GCP_CRED > cred_file
    gcloud auth login --cred-file=cred_file
    gcloud compute ssh --zone $GCP_CE_ZONE $GCP_INSTANCE
    if [ ! -d $GIT_FOLDER ]; then
        ls ~/.ssh/
        git clone git@github.com:CS428-Group5/cs428-backend.git
        cd $GIT_FOLDER
        python3 -m venv .env
        source .env/bin/activate
        pip install -r requirements.txt
        python3 manage.py migrate
        python3 manage.py runserver
    else
        cd $GIT_FOLDER
        git pull origin master
    fi
    
options:
  logging: GCS_ONLY
    
    

