# Generated by Django 4.2.2 on 2023-07-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_is_mentor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="current_title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
