# Generated by Django 4.2.2 on 2023-07-31 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0012_mentorsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.TextField()),
                ('cancelled_by', models.SmallIntegerField(choices=[(None, 'Not canceled'), (1, 'Mentor canceled'), (2, 'Mentee canceled')], default=None)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mentee')),
                ('mentor_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.mentorsession')),
            ],
        ),
    ]
