# Generated by Django 4.2.2 on 2023-07-31 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_mentorsession'),
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='BookedSession',
        ),
        migrations.CreateModel(
            name='MentorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_time', models.TimeField()),
                ('session_date', models.DateField()),
                ('is_book', models.BooleanField(default=False)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mentor')),
            ],
        ),
        migrations.AlterField(
            model_name='bookedsession',
            name='mentor_session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='session.mentorsession'),
        ),
    ]
