# Generated by Django 4.2.2 on 2023-07-31 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_rename_session_bookedsession_mentorsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedsession',
            name='cancelled_by',
            field=models.SmallIntegerField(choices=[(0, 'Not canceled'), (1, 'Mentor canceled'), (2, 'Mentee canceled')], default=0),
        ),
        migrations.AlterField(
            model_name='bookedsession',
            name='mentor_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.mentorsession'),
        ),
    ]
