# Generated by Django 4.2.2 on 2023-08-02 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_alter_bookedsession_cancelled_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedsession',
            name='event_link',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bookedsession',
            name='mentor_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='session.mentorsession'),
        ),
    ]
