# Generated by Django 4.2.2 on 2023-08-02 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_bookedsession_event_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedsession',
            name='mentor_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='session.mentorsession'),
        ),
    ]
