# Generated by Django 4.2.2 on 2023-08-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_alter_bookedsession_mentor_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedsession',
            name='event_id',
            field=models.TextField(null=True),
        ),
    ]
