# Generated by Django 4.2.2 on 2023-08-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_alter_bookedsession_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedsession',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='bookedsession',
            name='event_link',
        ),
        migrations.AddField(
            model_name='bookedsession',
            name='booked_date',
            field=models.DateField(null=True),
        ),
    ]
