# Generated by Django 4.2.2 on 2023-08-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_remove_bookedsession_event_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedsession',
            name='booked_date',
            field=models.DateTimeField(null=True),
        ),
    ]
