# Generated by Django 4.2.2 on 2023-08-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0008_alter_bookedsession_booked_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedsession',
            name='booked_date',
            field=models.DateField(null=True),
        ),
    ]
