# Generated by Django 4.2.2 on 2023-08-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0009_alter_bookedsession_booked_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedsession',
            name='booked_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=13, null=True),
        ),
    ]
